=== watfordsuzy/stencil/Generation/Tools/Stencil.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="items">
		<xs:complexType>
			<xs:sequence>
				<xs:choice maxOccurs="unbounded" minOccurs="1">
					<xs:element maxOccurs="unbounded" minOccurs="1" name="item">
						<xs:complexType>
							<xs:choice maxOccurs="unbounded">
                <xs:element minOccurs="0" maxOccurs="unbounded" name="indexfield">
                  <xs:complexType mixed="true">
                    <xs:attribute name="type" type="xs:string" use="required">
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Type of property in C#</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedReferenceField" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">The remote field to use when computedBy is set to Extra</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="isNullable" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">In C# will make nullable type if needed.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="notAnalyzed" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Indicates that this field should not be analyzed and only be searchable by exact match</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="friendlyName" type="xs:string" use="required" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Display name used anytime the item is referenced in a textual context. </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedFrom" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">If provided, the field is calculated by looking at this entity using the computedField and computedBy fields for instructions</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedField" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">The field on the foreign entity to use in the computedBy. Used with computedFrom and computed fields. </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedBy" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">The computation mechanism when computing fields. Currently supports: Null, NotNull, Count, Extra</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="sortable" type="xs:string" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">Sets whether this field will generate a special sortable index suffix in ElasticSearch that supports sorting. ie: field_name.sort </xs:documentation></xs:annotation>
                    </xs:attribute>
                  </xs:complexType>
                </xs:element>
								<xs:element minOccurs="1" maxOccurs="unbounded" name="field">
									<xs:complexType mixed="true">
                    
										<xs:attribute name="type" type="xs:string" use="required">
                      <xs:annotation><xs:documentation xml:lang="en">Type of property in C#</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="dbType" type="xs:string" use="required">
                      <xs:annotation><xs:documentation xml:lang="en">Type of SQL column</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="foreignKey" type="xs:string" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">The name of the entity that this field is referencing</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="foreignKeyField" type="xs:string" use="optional">
                      <xs:annotation><xs:documentation xml:lang="en">The column to reference on the foreign table</xs:documentation></xs:annotation>
                    </xs:attribute>
										<xs:attribute name="isNullable" type="xs:boolean" use="required" >
                      <xs:annotation><xs:documentation xml:lang="en">In sql creates the column as nullable. In C# will make nullable type if needed.</xs:documentation></xs:annotation>
                    </xs:attribute>
										<xs:attribute name="friendlyName" type="xs:string" use="required" >
                      <xs:annotation><xs:documentation xml:lang="en">Display name used anytime the item is referenced in a textual context. Warning: ForeignKeys use this name as a method name, so no spaces or special characters</xs:documentation></xs:annotation>
                    </xs:attribute>
										<xs:attribute name="uiListHidden" type="xs:boolean" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">UIHelpers use this to prevent this field from showing in the list view.</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="uiEditHidden" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">UIHelpers use this to prevent this field from showing in the edit view.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="uiCreateHidden" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">UIHelpers use this to prevent this field from showing in the edit view.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="searchable" type="xs:boolean" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">Sets whether this field should be included in general "Find" mechanisms</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="sortable" type="xs:string" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">Sets whether this field will generate a special sortable index suffix in ElasticSearch that supports sorting. ie: field_name.sort </xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="sdkHidden" type="xs:boolean" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">Prevents the field from being added to the SDK model</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="derivedProperty" type="xs:string" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">Created the property as a Derived property on the domain model. Used as an alternative to attached properties. Indicates the property will not always be populated.</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="facadeMapping" type="xs:string" use="optional" >
                      <xs:annotation><xs:documentation xml:lang="en">You with to customize the mapping between SDK and Domain. [useful for ui only or special payload processing]</xs:documentation></xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="indexExact" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Makes the field not be analyzed by elastic seach. Can only be matched by exact term.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="generateTokenIfEmpty" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">Reserved for Future Use</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="iInvalidateforeignKey" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">If true, when the current entity changes, it will invalidate the referenced ForeignKey. Note: only works on foreignKey fields</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="foreignKeyInvalidatesMe" type="xs:boolean" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">If true, when the foreign entity changes, it will invalidate this entity. Note: only works on foreignKey fields</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>

                    <xs:attribute name="computedFrom" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">If provided, the field is calculated by looking at this entity using the computedField and computedBy fields for instructions</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedField" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">The field on the foreign entity to use in the computedBy. Used with computedFrom and computed fields. </xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedBy" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">The computation mechanism when computing fields. Currently supports: Null, NotNull, Count, Extra</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="computedReferenceField" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">The remote field to use when computedBy is set to Extra</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                    <xs:attribute name="ukGroup" type="xs:string" use="optional" >
                      <xs:annotation>
                        <xs:documentation xml:lang="en">A sql unique key is generated for every field in this entity that matches the name provided.</xs:documentation>
                      </xs:annotation>
                    </xs:attribute>
                  </xs:complexType>
								</xs:element>
                
							</xs:choice>


              <xs:attribute name="indexForSearchable" type="xs:boolean" use="optional" >
                <xs:annotation>
                  <xs:documentation xml:lang="en">When the item is indexed, it will ensure that the entity has merged into the index and is available for searching.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
			        <xs:attribute name="name" type="xs:string" use="required" >
                <xs:annotation><xs:documentation xml:lang="en">The name of the entity, represents the C# class name and table name</xs:documentation></xs:annotation>
              </xs:attribute>
              <xs:attribute name="friendlyName" type="xs:string" use="required" >
                <xs:annotation><xs:documentation xml:lang="en">Display name used anytime the item is referenced in a textual context</xs:documentation></xs:annotation>
              </xs:attribute>
              <xs:attribute name="uiDisplayField" type="xs:string" use="optional" >
                <xs:annotation><xs:documentation xml:lang="en">The field whose value is shown in a UI that only supports a single field</xs:documentation></xs:annotation>
              </xs:attribute>
              <xs:attribute name="uiDefaultSort" type="xs:string" use="optional" >
                <xs:annotation><xs:documentation xml:lang="en">The field to sort by when not provided. Note: Not used in every capacity, UI is expected to always provide their preference.</xs:documentation></xs:annotation>
              </xs:attribute>
              <xs:attribute name="sdkBase" type="xs:boolean" use="optional">
                <xs:annotation>
                  <xs:documentation xml:lang="en">Creates a base class to allow for custom properties</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="useIndex" type="xs:boolean" use="optional">
                <xs:annotation>
                  <xs:documentation xml:lang="en">Whether this entity support index synchronization.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              <xs:attribute name="indexPriority" type="xs:integer" use="optional">
                <xs:annotation>
                  <xs:documentation xml:lang="en">The indexing priority that the synchronizers will use to synchronize data. Important for nested or dependant objects.</xs:documentation>
                </xs:annotation>
              </xs:attribute>
              
            </xs:complexType>
					</xs:element>
          <xs:element maxOccurs="unbounded" minOccurs="1" name="enum">
          </xs:element>
				</xs:choice>
			</xs:sequence>
      
      <xs:attribute name="projectName" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">Name used in all file paths and namespaces</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="schema" type="xs:string" use="required">
        <xs:annotation>
          <xs:documentation xml:lang="en">SQL Schema prefix NOT FULLY RESPECTED!</xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
      
		</xs:complexType>
	</xs:element>
</xs:schema>

=== watfordsuzy/stencil/Generation/XML/Entities.xml
<?xml version="1.0" encoding="utf-8"?>
<items schema="dbo" projectName="Stencil" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Tools\Stencil.xsd">
  <item name="GlobalSetting" friendlyName="Global Setting" uiDisplayField="name">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="GlobalSetting ID">global_setting_id</field>
    <field type="string" dbType="nvarchar(100)" isNullable="false" searchable="true" friendlyName="Name">name</field>
    <field type="string" dbType="nvarchar(max)" isNullable="true" friendlyName="Value">value</field>
  </item>
  <item name="Account" friendlyName="Account" uiDisplayField="first_name" useIndex="true" indexPriority="10" >
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Account ID">account_id</field>
    <field type="string" dbType="nvarchar(250)" isNullable="false" searchable="true" sortable="true" friendlyName="E-mail">email</field>
    <field type="string" dbType="nvarchar(250)" isNullable="false" uiListHidden="true" friendlyName="Password">password</field>
    <field type="string" dbType="nvarchar(50)" isNullable="false" uiListHidden="true" generateTokenIfEmpty="true" friendlyName="Password Salt">password_salt</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Is Disabled">disabled</field>
    <field type="string" dbType="nvarchar(50)" isNullable="false" uiListHidden="true" ukGroup="account_key" generateTokenIfEmpty="true" friendlyName="API Key">api_key</field>
    <field type="string" dbType="nvarchar(50)" isNullable="false" uiListHidden="true" generateTokenIfEmpty="true" friendlyName="API Secret">api_secret</field>
    <field type="string" dbType="nvarchar(50)" isNullable="true" sortable="true" friendlyName="First Name">first_name</field>
    <field type="string" dbType="nvarchar(50)" isNullable="true" sortable="true" friendlyName="Last Name">last_name</field>
    <field type="string" dbType="nvarchar(250)" isNullable="true" friendlyName="Entitlements">entitlements</field>
    <field type="string" dbType="nvarchar(50)" isNullable="true" uiListHidden="true" generateTokenIfEmpty="true" friendlyName="Password Reset Token">password_reset_token</field>
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="true" uiListHidden="true" friendlyName="Password Reset Date">password_reset_utc</field>
    <field type="string" dbType="nvarchar(100)" isNullable="true" uiListHidden="true" friendlyName="Push Token IOS">push_ios</field>
    <field type="string" dbType="nvarchar(100)" isNullable="true" uiListHidden="true" friendlyName="Push Token Google">push_google</field>
    <field type="string" dbType="nvarchar(100)" isNullable="true" uiListHidden="true" friendlyName="Push Token Microsoft">push_microsoft</field>
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="true" sortable="true" friendlyName="Last Login">last_login_utc</field>
    <field type="string" dbType="nvarchar(250)" isNullable="true" sortable="true" friendlyName="Last Login Platform">last_login_platform</field>
  </item>
  <!-- Products have a Product Owner (Account) -->
  <item name="Product" friendlyName="Product" uiDisplayField="product_name" useIndex="true" indexPriority="20">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Product ID">product_id</field>
    <field type="string" dbType="nvarchar(250)" isNullable="false" searchable="true" sortable="true" friendlyName="Name">product_name</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Account" foreignKeyField="account_id" friendlyName="ProductOwnerID">product_owner_id</field>
    <field type="string" dbType="nvarchar(max)" isNullable="true" searchable="true" sortable="false" friendlyName="Description">product_description</field>
    <indexfield type="int" isNullable="false" friendlyName="VersionCount" computedFrom="ProductVersion" computedField="product_id" computedBy="Count">version_count</indexfield>
  </item>
  <!-- Product Versions run on Platforms -->
  <item name="Platform" friendlyName="Platform" uiDisplayField="platform_name" useIndex="true" indexPriority="30">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Platform ID">platform_id</field>
    <field type="string" dbType="nvarchar(250)" isNullable="false" searchable="true" sortable="true" friendlyName="Name">platform_name</field>
    <field type="Bitness" dbType="int" isNullable="false" sortable="true" friendlyName="Bitness">bitness</field>
  </item>
  <!-- Products have Product Versions -->
  <item name="ProductVersion" friendlyName="Product Version" uiDisplayField="version" useIndex="true" indexPriority="40">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Product Verison ID">product_version_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Product" foreignKeyField="product_id" iInvalidateforeignKey="true" friendlyName="ProductID">product_id</field>
    <field type="string" dbType="nvarchar(250)" isNullable="false" searchable="true" sortable="true" friendlyName="Version">version</field>
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="true" sortable="true" friendlyName="Release Date">release_date_utc</field>
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="true" sortable="true" friendlyName="End of Life Date">end_of_life_date_utc</field>
    <indexfield type="string" isNullable="false" sortable="true" friendlyName="ProductName" computedFrom="Product" computedField="product_name" computedBy="Extra">product_name</indexfield>
  </item>
  <!--<item name="ProductVersionPlatform" friendlyName="Product Version Platform" useIndex="true" indexPriority="60">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Product Verison Platform ID">product_version_platform_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="ProductVersion" foreignKeyField="product_version_id" friendlyName="Product Verison ID">product_version_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" foreignKey="Platform" foreignKeyField="platform_id" friendlyName="Platform ID">platform_id</field>
  </item>
  <item name="Ticket" friendlyName="Ticket" uiDisplayField="ticket_description" useIndex="true" indexPriority="40">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Ticket ID">ticket_id</field>
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Reporter ID" foreignKey="Account" foreignKeyField="account_id">reporter_id</field>
  </item>-->
  <item name="Asset" friendlyName="Asset" uiDisplayField="asset_id" trackUpdates="true">
    <field type="Guid" dbType="uniqueidentifier" isNullable="false" friendlyName="Asset ID">asset_id</field>
    <field type="AssetType" dbType="int" isNullable="false" friendlyName="Asset Type">type</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Available">available</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Should Resize">resize_required</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Should Encode">encode_required</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Is Resizing">resize_processing</field>
    <field type="bool" dbType="bit" isNullable="false" friendlyName="Is Encoding">encode_processing</field>
    <field type="string" dbType="nvarchar(10)" isNullable="true" friendlyName="Thumb Small Dimensions">thumb_small_dimensions</field>
    <field type="string" dbType="nvarchar(10)" isNullable="true" friendlyName="Thumb Medium Dimensions">thumb_medium_dimensions</field>
    <field type="string" dbType="nvarchar(10)" isNullable="true" friendlyName="Thumb Large Dimensions">thumb_large_dimensions</field>
    <field type="string" dbType="nvarchar(50)" isNullable="true" friendlyName="Resize Status">resize_status</field>
    <field type="int" dbType="int" isNullable="false" friendlyName="Resize Attempts">resize_attempts</field>
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="true" friendlyName="Resize Attempt">resize_attempt_utc</field>
    <field type="string" dbType="nvarchar(50)" isNullable="true" friendlyName="Encode Identifier">encode_identifier</field>
    <field type="string" dbType="nvarchar(50)" isNullable="true" friendlyName="Encode Status">encode_status</field>
    <field type="string" dbType="nvarchar(512)" isNullable="true" friendlyName="Raw Url">raw_url</field>
    <field type="string" dbType="nvarchar(512)" isNullable="true" friendlyName="Public Url">public_url</field>
    <field type="string" dbType="nvarchar(512)" isNullable="true" friendlyName="Thumb Url Small">thumb_small_url</field>
    <field type="string" dbType="nvarchar(512)" isNullable="true" friendlyName="Thumb Url Medium">thumb_medium_url</field>
    <field type="string" dbType="nvarchar(512)" isNullable="true" friendlyName="Thumb Url Large">thumb_large_url</field>
    <field type="string" dbType="nvarchar(max)" isNullable="true" friendlyName="Encode Log">encode_log</field>
    <field type="string" dbType="nvarchar(max)" isNullable="true" friendlyName="Resize Log">resize_log</field>
    <field type="Dependency" dbType="int" isNullable="false" friendlyName="Dependencies">dependencies</field>
    <field type="int" dbType="int" isNullable="false" friendlyName="Encode Attempts">encode_attempts</field>
    <field type="DateTime" dbType="datetimeoffset(0)" isNullable="true" friendlyName="Encode Attempt">encode_attempt_utc</field>
    <field type="string" dbType="nvarchar(20)" isNullable="true" friendlyName="Resize Mode">resize_mode</field>
  </item>
  <enum name="AssetType">
    <field value="0">Image</field>
    <field value="1">Video</field>
  </enum>
  <enum name="Dependency">
